### PR TITLE
Ionic 3.1.x update

### PR DESCRIPTION
**Pull request by leoruhland**
Ionic refactor: https://github.com/driftyco/ionic/commit/59eb9a328d353326540d767921057a887058d66f#diff-398257840976a25db8f35174d4d9d467L5

### CODE REVIEW

**Comment by WolfWalter** [comment]
Works for me

**Comment by burger1992** [comment]
same here I was gonna open a PR. thanks @leoruhland

**Comment by Riron** [comment]
Thanks for the PR 👍 
I'll look at it quickly and release a new version as fast as possible.

**Comment by leoruhland** [comment]
Thank you @Riron, for this amazing component!

**Comment by RedEars** [comment]
@leoruhland Does it work for you? Your change removed the import error, but when I click on the image nothing happens. Ionic 3.0.1

**Comment by danielkkelly** [comment]
Tested using 3.1.0 and it works well for us.  @leoruhland - thank you!

**Comment by Riron** [comment]
Thanks @leoruhland for the PR 👍

**Pull request merged**
